### ISSUE TITLE
PyQt6 tutorial Widgets example QCheckBox doesn't work 

### ISSUE THREAD

**Issue by fossildoc** [pythonguis/feedback#2]
The statement
print(s == Qt.CheckState.Checked)
will always return False because s is an integer but Qt.CheckState.Checked is an enum.

The statement should be:
print(s == Qt.CheckState.Checked.value)

This was posted on StackOverflow 1 year 10 months ago.

Also, in the text it says:
"...you can use state == Qt.Checked."
This does not work because Qt does not have an attribute "Checked".

**Comment by mfitzp** [comment]
Fixed, thanks @fossildoc
