### ISSUE TITLE
Example code corrupted in Tkinter Place Layout tutorial

### ISSUE THREAD

**Issue by greblosdier** [pythonguis/feedback#20]
On page: [https://www.pythonguis.com/tutorials/create-ui-with-tkinter-place-layout-manager/](https://www.pythonguis.com/tutorials/create-ui-with-tkinter-place-layout-manager/)

On line 29 of the example code it reads:
`lb_of_cities.bind("&lt;&lt;ListboxSelect&gt;&gt;", lambda event:  get_selection())`

When it should read:
`lb_of_cities.bind("<<ListboxSelect>>", lambda event: get_selection())`

**Comment by mfitzp** [comment]
Thanks, fixed!
