### ISSUE TITLE
Misspelled expression in the PyQt6 tutorial

### ISSUE THREAD

**Issue by JCionx** [pythonguis/feedback#29]
In the [Create your first app with PyQt6 tutorial](https://www.pythonguis.com/tutorials/pyqt6-creating-your-first-window/) there's a misspelled Python expression in the **Stepping through the code**.

This is the sentence that contains the misspelled expression:

> Next we create an instance of `QApplication`, passing in `sys.arg`, which is Python `list` containing the command line arguments passed to the application.

In this sentence, the `sys.arg` expression is incorrect, and should instead be `sys.argv`.

Here is a screenshot that shows the sentence where the expression is:

![Screenshot 2024-11-20 at 10 29 38](https://github.com/user-attachments/assets/8ce4866a-cf8b-4822-a53e-3a9055c3eb42)

Thanks for the great tutorial! Just wanted to point out a small typo.

**Comment by lpozo** [comment]
https://github.com/pythonguis/pythonguis/pull/176
