### ISSUE TITLE
Extraneous text?

### ISSUE THREAD

**Issue by RobCSPS** [pythonguis/feedback#4]
In [this page of the PySide6 tutorial](https://www.pythonguis.com/tutorials/pyside6-creating-your-first-window/) there is text explaining why an underscore is present, however there is no underscore to be explained. The text appears at the end of the section titled "What's the event loop?". Search for the first appearance of the string "underscore" and you'll find it.

**Comment by mfitzp** [comment]
Fixed, thanks!
