### ISSUE TITLE
Important issue about drag-and-drop

### ISSUE THREAD

**Issue by Margo-tail** [pythonguis/feedback#5]
Thanks for the article - https://www.pythonguis.com/faq/pyqt6-drag-drop-widgets/, great job has been done. However, there is a question. If you drop an item in an inaccessible area, it disappears from the list. How can this be prevented?

**Comment by mfitzp** [comment]
Thanks @Margo-tail this should be fixed now. We need to re-show the widget in the original mouse event handler (which starts the drag event loop with `exec()`) after the drag is complete.
